name: Create Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release:
    name: Create Automated Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Run linting
        run: npm run lint || echo "Linting completed with warnings"

      - name: Bump version
        id: bump_version
        run: |
          node scripts/bump-version.js ${{ github.event.inputs.bump_type }}
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }}

          🤖 Generated with [Claude Code](https://claude.ai/code)

          Co-Authored-By: Claude <noreply@anthropic.com>"

      - name: Push changes
        run: git push origin main

      - name: Create and push tag
        run: |
          git tag ${{ steps.bump_version.outputs.tag_name }}
          git push origin ${{ steps.bump_version.outputs.tag_name }}

      - name: Wait for release workflow
        run: |
          echo "Waiting for release workflow to complete..."
          sleep 30  # Give the release workflow time to start

      - name: Check release workflow status
        run: |
          echo "Release workflow should now be running at:"
          echo "https://github.com/${{ github.repository }}/actions/workflows/release.yml"
          echo "Tag created: ${{ steps.bump_version.outputs.tag_name }}"
          echo "New version: ${{ steps.bump_version.outputs.new_version }}"