name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  validate:
    name: Validate Release and Build APK
    uses: ./.github/workflows/ci.yml
    with:
      build_release: true
    secrets: inherit

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download release APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: ./apk/

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            # Extract changelog for current version
            sed -n "/## \[v\?${{ steps.version.outputs.VERSION }}\]/,/## \[v\?[0-9]/p" CHANGELOG.md | head -n -1 > current_changelog.md
            if [ -s current_changelog.md ]; then
              echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
              cat current_changelog.md >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
            else
              echo "CHANGELOG=Release v${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "CHANGELOG=Release v${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Obtainium metadata
        run: |
          # Extract actual version code from the built APK
          ACTUAL_VERSION_CODE=$(git rev-list --count HEAD)
          echo "Version code for release: $ACTUAL_VERSION_CODE"
          
          # Validate version code is reasonable
          if [ "$ACTUAL_VERSION_CODE" -lt 100 ]; then
            echo "ERROR: Version code is too low ($ACTUAL_VERSION_CODE) for release"
            exit 1
          fi
          
          cat > obtainium.json << EOF
          {
            "name": "Mobdeck",
            "version": "${{ steps.version.outputs.VERSION }}",
            "versionCode": "$ACTUAL_VERSION_CODE",
            "apkUrl": "https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.VERSION }}/app-universal-release.apk",
            "releaseDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "changelog": "${{ steps.changelog.outputs.CHANGELOG }}",
            "minSdkVersion": 24,
            "targetSdkVersion": 34,
            "packageName": "com.mobdeck"
          }
          EOF

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Mobdeck v${{ steps.version.outputs.VERSION }}
          body: |
            # Mobdeck Mobile App v${{ steps.version.outputs.VERSION }}

            ${{ steps.changelog.outputs.CHANGELOG }}

            ## Installation

            ### Direct APK Installation
            1. Download the APK file below
            2. Enable "Install from unknown sources" in your Android settings
            3. Install the APK file

            ### Obtainium (Recommended)
            Add this repository to Obtainium for automatic updates:
            ```
            https://github.com/${{ github.repository }}
            ```

            ## Compatibility
            - Android 7.0+ (API level 24+)
            - Requires self-hosted Readeck instance

            ## Verification
            - APK SHA256: `${{ hashFiles('./apk/app-universal-release.apk') }}`
            - Built from commit: `${{ github.sha }}`

          files: |
            ./apk/app-universal-release.apk
            obtainium.json
          draft: false
          prerelease: false
          generate_release_notes: false
